let a: number = 20;
console.log(a);
let c: string | number | boolean = true;
console.log(c);
let b: number[] = [1, 2, 3];
console.log(b);
let d: [number, string, boolean, string] = [1, "hello", true, "world"];
console.log(d);
let e: any = "This can be any type";
console.log(e);
let f:(number | string)[] = [1, "two", 3, "four"];
console.log(f);
let g:Set<number> = new Set();
g.add(4);
g.delete(2);
console.log(g);
let h: Map<string, number> = new Map();
h.set("one", 1);
h.set("two", 2);
console.log(h);